# wrangler.toml

# The name of your Cloudflare Worker.
name = "foodgrind-image-generator"

# The entry point for your Worker's source code.
# This correctly points to our new modular structure.
main = "src/index.js"

# The compatibility date ensures your Worker runs on a stable version of the runtime.
compatibility_date = "2024-03-20"

# This is the correct block for binding an R2 bucket.
# It makes the bucket named "foodgrind-image-storage" available
# in your code under the variable `env.IMAGE_BUCKET`.
[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "foodgrind-image-storage"

# Add this block to bind a KV namespace
[[kv_namespaces]]
binding = "TEXT_CACHE"
id = "9f7892da1d90486196e588cff983712f"

[observability.logs]
enabled = true
